### ISSUE TITLE
ErrorException: Trying to get property 'methods' of non-object in EmbeddedAssetsLinkService

### ISSUE THREAD

**Issue by craftedsystems** [marionnewlevant/craft-embedded_assets_link#4]
I got the message _A server error occured._ in the Craft control panel and found this in the _web.log_.

```
[error][yii\base\ErrorException:8] yii\base\ErrorException: 
Trying to get property 'methods' of non-object in 
/dist/vendor/marionnewlevant/embedded-assets-link/src/services/EmbeddedAssetsLinkService.php:37
```

```
$embeddedAsset = EmbeddedAssets::$plugin->methods->getEmbeddedAsset($element);
```

This error pops up anytime I select an asset.

Craft v3.5.16
PHP v7.4.13
Plugin v1.0.2

**Comment by marionnewlevant** [comment]
Fixed with v 1.0.3 - this was an error that happened when Embedded Assets Link plugin installed, but not Embedded Assets plugin
